CREATE DATABASE TRAINING;
USE TRAINING;
CREATE TABLE DETAILS(
NAME VARCHAR(20),
AGE INT,
EMPID INT PRIMARY KEY);
SELECT * FROM DETAILS;
INSERT INTO DETAILS VALUES("SAM",22,3);
INSERT INTO DETAILS VALUES("MAY",20,8);
INSERT INTO DETAILS VALUES("FARA",26,1);
INSERT INTO DETAILS VALUES("ZEN",29,5);
SELECT * FROM COURSE;

CREATE TABLE COURSE(
COURSE_NAME VARCHAR(20),
EMPID INT,
ID INT PRIMARY KEY
);
INSERT INTO COURSE VALUES("PYTHON",3,10);
INSERT INTO COURSE VALUES("JAVA",8,15);
SELECT DETAILS.NAME, COURSE.COURSE_NAME
FROM DETAILS
INNER JOIN COURSE ON DETAILS.EMPID=COURSE.EMPID;
SELECT DETAILS.NAME, COURSE.COURSE_NAME
FROM DETAILS
LEFT JOIN COURSE ON DETAILS.EMPID=COURSE.EMPID;
SELECT DETAILS.NAME, COURSE.COURSE_NAME
FROM DETAILS
RIGHT JOIN COURSE ON DETAILS.EMPID=COURSE.EMPID;
SELECT DETAILS.NAME, COURSE.COURSE_NAME
FROM DETAILS
LEFT JOIN COURSE ON DETAILS.EMPID=COURSE.EMPID
UNION
SELECT DETAILS.NAME, COURSE.COURSE_NAME
FROM DETAILS
RIGHT JOIN COURSE ON DETAILS.EMPID=COURSE.EMPID;
